"""buzzkit — Python bindings + async client for Block's Buzz (Nostr) protocol.

Low-level event building/signing/verification is done in Rust (``buzz-core`` /
``buzz-sdk``); all network I/O is pure Python. Use the module-level functions for
one-off event work, or :class:`BuzzClient` for a managed async relay connection.

This is an independent, unofficial project — not affiliated with Block, Inc.
"""

from __future__ import annotations

from importlib.metadata import version as _version

from ._native import (
    HUDDLE_FRAME_SAMPLES,
    HUDDLE_PROTOCOL_VERSION,
    HUDDLE_SAMPLE_RATE,
    KIND_ADD_MEMBER,
    KIND_AUTH,
    KIND_CREATE_CHANNEL,
    KIND_DELETE_MESSAGE,
    KIND_DELETION,
    KIND_EDIT_METADATA,
    KIND_HTTP_AUTH,
    KIND_HUDDLE_ENDED,
    KIND_HUDDLE_PARTICIPANT_JOINED,
    KIND_HUDDLE_PARTICIPANT_LEFT,
    KIND_HUDDLE_STARTED,
    KIND_LEAVE_CHANNEL,
    KIND_MANAGED_AGENT,
    KIND_MESSAGE_EDIT,
    KIND_PRESENCE_UPDATE,
    KIND_REACTION,
    KIND_STREAM_MESSAGE,
    KIND_STREAM_MESSAGE_V2,
    KIND_USER_STATUS,
    HuddleDecoder,
    HuddleEncoder,
    build_auth_event,
    build_create_channel_event,
    build_delete_message_event,
    build_edit_event,
    build_huddle_started_event,
    build_join_channel_event,
    build_leave_event,
    build_message_event,
    build_presence_event,
    build_profile_event,
    build_reaction_event,
    build_remove_reaction_event,
    build_set_topic_event,
    build_user_status_event,
    compute_auth_tag,
    generate_keypair,
    pubkey_from_secret,
    sign_nip98,
    verify_auth_tag,
    verify_event,
)
from .agents import OWNER_COMMANDS, parse_owner_command, verify_agent_profile
from .client import BuzzClient
from .huddle import (
    HuddleAudio,
    HuddleClient,
    HuddleError,
    HuddleEvent,
    HuddlePeerJoined,
    HuddlePeerLeft,
)

__version__ = _version("buzzkit")

__all__ = [
    "HUDDLE_FRAME_SAMPLES",
    "HUDDLE_PROTOCOL_VERSION",
    "HUDDLE_SAMPLE_RATE",
    "KIND_ADD_MEMBER",
    "KIND_AUTH",
    "KIND_CREATE_CHANNEL",
    "KIND_DELETE_MESSAGE",
    "KIND_DELETION",
    "KIND_EDIT_METADATA",
    "KIND_HTTP_AUTH",
    "KIND_HUDDLE_ENDED",
    "KIND_HUDDLE_PARTICIPANT_JOINED",
    "KIND_HUDDLE_PARTICIPANT_LEFT",
    "KIND_HUDDLE_STARTED",
    "KIND_LEAVE_CHANNEL",
    "KIND_MANAGED_AGENT",
    "KIND_MESSAGE_EDIT",
    "KIND_PRESENCE_UPDATE",
    "KIND_REACTION",
    "KIND_STREAM_MESSAGE",
    "KIND_STREAM_MESSAGE_V2",
    "KIND_USER_STATUS",
    "OWNER_COMMANDS",
    "BuzzClient",
    "HuddleAudio",
    "HuddleClient",
    "HuddleDecoder",
    "HuddleEncoder",
    "HuddleError",
    "HuddleEvent",
    "HuddlePeerJoined",
    "HuddlePeerLeft",
    "build_auth_event",
    "build_create_channel_event",
    "build_delete_message_event",
    "build_edit_event",
    "build_huddle_started_event",
    "build_join_channel_event",
    "build_leave_event",
    "build_message_event",
    "build_presence_event",
    "build_profile_event",
    "build_reaction_event",
    "build_remove_reaction_event",
    "build_set_topic_event",
    "build_user_status_event",
    "compute_auth_tag",
    "generate_keypair",
    "pubkey_from_secret",
    "sign_nip98",
    "parse_owner_command",
    "verify_agent_profile",
    "verify_auth_tag",
    "verify_event",
]
